# fly.toml app configuration file generated for red-thunder-8099 on 2023-06-29T11:05:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-thunder-8099"
primary_region = "sin"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"
