name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        id: commits
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: |
          echo join($COMMIT_MESSAGES,",")
          echo contains("$COMMIT_MESSAGES","#skip")
